### ISSUE TITLE
NullPointerException in android sdk 5.0.1

### ISSUE THREAD

**Issue by viniciusguardieirozup** [ZupIT/beagle#1023]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
App crash when is on second plan with NullPointerException on Android sdk 5.0.1 

## Information

```Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'kotlin.reflect.jvm.internal.impl.load.kotlin.KotlinJvmBinaryClass$MethodAnnotationVisitor kotlin.reflect.jvm.internal.impl.load.kotlin.KotlinJvmBinaryClass$MemberVisitor.visitMethod(kotlin.reflect.jvm.internal.impl.name.Name, java.lang.String)' on a null object reference
       at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.loadMethodAnnotations(ReflectClassStructure.java:97)
       at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.visitMembers(ReflectClassStructure.java:90)
       at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClass.visitMembers(ReflectKotlinClass.java:71)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadAnnotationsAndInitializers(AbstractBinaryClassAnnotationAndConstantLoader.java:304)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.access$loadAnnotationsAndInitializers(AbstractBinaryClassAnnotationAndConstantLoader.java:40)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader$storage$1.invoke(AbstractBinaryClassAnnotationAndConstantLoader.java:45)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader$storage$1.invoke(AbstractBinaryClassAnnotationAndConstantLoader.java:40)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:446)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:521)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.findClassAndLoadMemberAnnotations(AbstractBinaryClassAnnotationAndConstantLoader.java:167)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.findClassAndLoadMemberAnnotations$default(AbstractBinaryClassAnnotationAndConstantLoader.java:152)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadPropertyAnnotations(AbstractBinaryClassAnnotationAndConstantLoader.java:119)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadCallableAnnotations(AbstractBinaryClassAnnotationAndConstantLoader.java:94)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer$getAnnotations$1.invoke(MemberDeserializer.java:369)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer$getAnnotations$1.invoke(MemberDeserializer.java:27)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:352)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:408)
       at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(StorageKt.java:42)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedAnnotations.getAnnotations(DeserializedAnnotations.java)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedAnnotations.iterator(DeserializedAnnotations.java:32)
       at kotlin.reflect.jvm.internal.UtilKt.computeAnnotations(UtilKt.java:208)
       at kotlin.reflect.jvm.internal.KCallableImpl$_annotations$1.invoke(KCallableImpl.java:34)
       at kotlin.reflect.jvm.internal.KCallableImpl$_annotations$1.invoke(KCallableImpl.java:21)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
       at kotlin.reflect.jvm.internal.KCallableImpl.getAnnotations(KCallableImpl.java:36)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapterFactory.java:242)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
       at br.com.zup.beagle.android.data.serializer.PolymorphicJsonAdapterFactory.create(PolymorphicJsonAdapterFactory.java:231)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapterFactory.java:254)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
       at br.com.zup.beagle.android.data.serializer.PolymorphicJsonAdapterFactory.create(PolymorphicJsonAdapterFactory.java:231)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:72)
       at br.com.zup.beagle.android.setup.BeagleSdk$init$1.invokeSuspend(BeagleSdk.java:66)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.java:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:740)```

**Comment by viniciusguardieirozup** [comment]
This issue already registered on issue #994
