### ISSUE TITLE
[Android] Beagle cache not working as expected

### ISSUE THREAD

**Issue by othiagosouto** [ZupIT/beagle#835]
#812 
 Description
We had a problem with a component with @RegisterWidget that was failing to deserialize and because of that we did remove the @RegisterAnnotation of the component and that should work as expected but we're receiving an BeagleApiException with 304, making the screen fail even without

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. App `AppBeagleConfig`  `cache` enabled 
2. Create a @RegisterWidget with component using some field with CharSequence like described on issue #715 
3. Install the app
4. Try to open some server driven screen and you're going to receive the problem related on issue #715 
5. Remove @RegisterWidget annotation from the component
6. build and install the app
7. Try to open the same server driven screen that previously you've tried to open.
## Expected Results
Load the screen as expected

## Actual result
Because of the following error described below, the only way to access the screen is to clear the cache or remove and install the app again.

```
    BeagleApiException(responseData=ResponseData(statusCode=304, data=[], headers={X-Correlation-Id=c63355ca17ee4552bc7baf4cff8b5982, X-Request-Id=891dd404f3dc4a8fbf2d6aa79e7e8b76, beagle-hash=d325e63b394abae0b6f8f9a72fbf2b4982e5b14f80e8772f384fb6fe573300655ca41efaf5eb37f4688d76af48a1faa8057abad0625bc4dcf14d05f131482b67, Date=Wed, 26 Aug 2020 21:34:50 GMT, Keep-Alive=timeout=60, Connection=keep-alive}, statusText=null), message=fetchData error for url http://10.0.2.2:8080/)
        at br.com.zup.beagle.android.data.BeagleApi$fetchData$$inlined$suspendCancellableCoroutine$lambda$1.invoke(BeagleApi.kt:50)
        at br.com.zup.beagle.android.data.BeagleApi$fetchData$$inlined$suspendCancellableCoroutine$lambda$1.invoke(BeagleApi.kt:29)
        at com.iti.serverdriven.network.httpclient.ServerDrivenHttpClient$execute$1.onResponse(ServerDrivenHttpClient.kt:44)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Obs: http://10.0.2.2:8080 is a local address that is hosting.

**Comment by othiagosouto** [comment]
It's an internal error here, beagle working as designed 👍
