### ISSUE TITLE
[Android] Error in sum function evaluation

### ISSUE THREAD

**Issue by paulomeurerzup** [ZupIT/beagle#877]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
There is an error while evaluating sum function

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Given the json below 
2. Start a new BeagleActivity

## Expected Results
Beagle should evaluate the sum function

## Code example, screenshot, or link to a repository:

JSON:
```
                     {
                       "_beagleComponent_":"beagle:screencomponent",
                       "child":
                       {
                         "_beagleComponent_": "beagle:listview",
                         "direction": "VERTICAL",
                         "useParentScroll": true,
                         "context": {
                           "id": "categories",
                           "value": []
                         },
                         "dataSource": "@{categories}",
                         "iteratorName": "category",
                         "onInit": [
                           {
                             "_beagleAction_": "beagle:sendRequest",
                             "url": "https://gist.githubusercontent.com/Tiagoperes/95f5900f956659e594d7c4a6d1b8a4c0/raw/3192187fd2f19fa3c3b483ae09efe44b9e2a9f90/categories.json",
                             "onSuccess": [
                               {
                                 "_beagleAction_": "beagle:setContext",
                                 "contextId":"categories",
                                 "value": "@{onSuccess.data}"
                               }
                             ]
                           }
                         ],
                         "template": {
                           "_beagleComponent_": "beagle:container",
                           "style": {
                             "margin": {
                               "bottom": {
                                 "value": 50,
                                 "type": "REAL"
                               }
                             }
                           },
                           "children": [
                             {
                               "_beagleComponent_": "beagle:text",
                               "text": "@{item.name}",
                               "style": {
                                 "margin": {
                                   "bottom": {
                                     "value": 20,
                                     "type": "REAL"
                                   }
                                 }
                               }
                             },
                             {
                               "_beagleComponent_": "beagle:listview",
                               "direction": "HORIZONTAL",
                               "scrollEndThreshold": 80,
                               "context": {
                                 "id": "moviePage",
                                 "value": {
                                   "page": 0,
                                   "total_pages": 0,
                                   "results": []
                                 }
                               },
                               "onInit": [
                                 {
                                   "_beagleAction_": "beagle:sendRequest",
                                   "url": "https://gist.githubusercontent.com/Tiagoperes/95f5900f956659e594d7c4a6d1b8a4c0/raw/3192187fd2f19fa3c3b483ae09efe44b9e2a9f90/@{category.path}.@{sum(moviePage.page, 1)}.json",
                                   "onSuccess": [
                                     {
                                       "_beagleAction_": "beagle:setContext",
                                       "contextId": "moviePage",
                                       "value": {
                                         "page": "@{onSuccess.data.page}",
                                         "total_pages": "@{onSuccess.data.total_pages}",
                                         "results": "@{union(moviePage.results, onSuccess.data.results)}"
                                       }
                                     }
                                   ]
                                 }
                               ],
                               "dataSource": "@{moviePage.results}",
                               "iteratorName": "movie",
                               "template": {
                                 "_beagleComponent_": "beagle:touchable",
                                 "onPress": [
                                   {
                                     "_beagleAction_": "beagle:alert",
                                     "message": "Title: @{movie.original_title}\nGenre: @{category.name}\nRelease date: @{movie.release_date}\nRating: @{movie.vote_average}\n\n@{movie.overview}"
                                   }
                                 ],
                                 "child":
                                   {
                                     "_beagleComponent_": "beagle:image",
                                     "path": {
                                       "_beagleImagePath_": "remote",
                                       "url": "https://image.tmdb.org/t/p/w500/@{movie.poster_path}"
                                     },
                                     "style": {
                                       "size": {
                                         "height": {
                                           "value": 240,
                                           "type": "REAL"
                                         }
                                       },
                                       "margin": {
                                         "right": {
                                           "value": 15,
                                           "type": "REAL"
                                         }
                                       }
                                     }
                                   }
                                 
                               }
                             }
                           ]
                         }
                       }
                    
                     }
```

ERROR LOG:

```
E/BeagleSDK: Error while trying to execute expression function.
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at br.com.zup.beagle.android.context.tokenizer.function.builtin.FunctionExtensionsKt.toListOfDoubles(FunctionExtensions.kt:23)
        at br.com.zup.beagle.android.context.tokenizer.function.builtin.number.SumFunction.execute(SumFunction.kt:29)
        at br.com.zup.beagle.android.context.tokenizer.function.builtin.number.SumFunction.execute(SumFunction.kt:23)
        at br.com.zup.beagle.android.context.tokenizer.function.FunctionResolver.execute(FunctionResolver.kt:38)
        at br.com.zup.beagle.android.context.tokenizer.ExpressionTokenExecutor.interpretFunction(ExpressionTokenExecutor.kt:62)
        at br.com.zup.beagle.android.context.tokenizer.ExpressionTokenExecutor.interpretToken(ExpressionTokenExecutor.kt:46)
        at br.com.zup.beagle.android.context.tokenizer.ExpressionTokenExecutor.execute(ExpressionTokenExecutor.kt:38)
        at br.com.zup.beagle.android.context.ContextDataEvaluation.evaluateExpression(ContextDataEvaluation.kt:134)
        at br.com.zup.beagle.android.context.ContextDataEvaluation.evaluateExpressionsForContext(ContextDataEvaluation.kt:100)
        at br.com.zup.beagle.android.context.ContextDataEvaluation.evaluateBindExpressions(ContextDataEvaluation.kt:65)
        at br.com.zup.beagle.android.context.ContextDataEvaluation.evaluateBindExpressions$default(ContextDataEvaluation.kt:57)
        at br.com.zup.beagle.android.context.ContextDataEvaluation.evaluateBindExpression(ContextDataEvaluation.kt:50)
        at br.com.zup.beagle.android.view.viewmodel.ScreenContextViewModel.evaluateExpressionForImplicitContext(ScreenContextViewModel.kt:60)
        at br.com.zup.beagle.android.utils.BindExtensionsKt.evaluateExpression(BindExtensions.kt:73)
        at br.com.zup.beagle.android.utils.BindExtensionsKt.evaluateBind(BindExtensions.kt:55)
        at br.com.zup.beagle.android.utils.BindExtensionsKt.evaluateForAction(BindExtensions.kt:43)
        at br.com.zup.beagle.android.utils.ActionExtensionsKt.evaluateExpression(ActionExtensions.kt:123)
        at br.com.zup.beagle.android.action.SendRequest.toSendRequestInternal(SendRequest.kt:101)
        at br.com.zup.beagle.android.action.SendRequest.execute(SendRequest.kt:72)
        at br.com.zup.beagle.android.components.ListView.executeOnInit(ListViewTwo.kt:129)
        at br.com.zup.beagle.android.components.ListView$registerOnAttachStateChangeListener$1.onViewAttachedToWindow(ListViewTwo.kt:116)
        at android.view.View.dispatchAttachedToWindow(View.java:19564)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5149)
        at android.view.ViewGroup.addView(ViewGroup.java:4935)
        at android.view.ViewGroup.addView(ViewGroup.java:4875)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:856)
        at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8601)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8559)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8547)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1641)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:24530)
        at br.com.zup.beagle.android.view.YogaLayout$ViewMeasureFunction.measure(YogaLayout.java:362)
        at com.facebook.yoga.YogaNodeJNIBase.measure(YogaNodeJNIBase.java:474)
E/BeagleSDK:     at com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayout(Native Method)
        at com.facebook.yoga.YogaNodeJNIBase.calculateLayout(YogaNodeJNIBase.java:182)
        at br.com.zup.beagle.android.view.YogaLayout.createLayout(YogaLayout.java:318)
        at br.com.zup.beagle.android.view.YogaLayout.onMeasure(YogaLayout.java:292)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3006)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1833)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2122)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    Could not found value for https://gist.githubusercontent.com/Tiagoperes/95f5900f956659e594d7c4a6d1b8a4c0/raw/3192187fd2f19fa3c3b483ae09efe44b9e2a9f90/@{category.path}.@{sum(moviePage.page, 1)}.json : class java.lang.String
```

**Comment by paulomeurerzup** [comment]
Fixed in 1.2.1-android patch
